In [5]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
a=pd.read_csv(r'‪C:\Users\JAY\Downloads\50_Startups.csv'.replace('\u202a', ''))
label_encoder = LabelEncoder()
a['State'] = label_encoder.fit_transform(a['State'])
print(a)

    R&D Spend  Administration  Marketing Spend  State     Profit
0   165349.20       136897.80        471784.10      2  192261.83
1   162597.70       151377.59        443898.53      0  191792.06
2   153441.51       101145.55        407934.54      1  191050.39
3   144372.41       118671.85        383199.62      2  182901.99
4   142107.34        91391.77        366168.42      1  166187.94
5   131876.90        99814.71        362861.36      2  156991.12
6   134615.46       147198.87        127716.82      0  156122.51
7   130298.13       145530.06        323876.68      1  155752.60
8   120542.52       148718.95        311613.29      2  152211.77
9   123334.88       108679.17        304981.62      0  149759.96
10  101913.08       110594.11        229160.95      1  146121.95
11  100671.96        91790.61        249744.55      0  144259.40
12   93863.75       127320.38        249839.44      1  141585.52
13   91992.39       135495.07        252664.93      0  134307.35
14  119943.24       15654

In [6]:
x=a.iloc[:,:-1].values
x

array([[1.6534920e+05, 1.3689780e+05, 4.7178410e+05, 2.0000000e+00],
       [1.6259770e+05, 1.5137759e+05, 4.4389853e+05, 0.0000000e+00],
       [1.5344151e+05, 1.0114555e+05, 4.0793454e+05, 1.0000000e+00],
       [1.4437241e+05, 1.1867185e+05, 3.8319962e+05, 2.0000000e+00],
       [1.4210734e+05, 9.1391770e+04, 3.6616842e+05, 1.0000000e+00],
       [1.3187690e+05, 9.9814710e+04, 3.6286136e+05, 2.0000000e+00],
       [1.3461546e+05, 1.4719887e+05, 1.2771682e+05, 0.0000000e+00],
       [1.3029813e+05, 1.4553006e+05, 3.2387668e+05, 1.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 2.0000000e+00],
       [1.2333488e+05, 1.0867917e+05, 3.0498162e+05, 0.0000000e+00],
       [1.0191308e+05, 1.1059411e+05, 2.2916095e+05, 1.0000000e+00],
       [1.0067196e+05, 9.1790610e+04, 2.4974455e+05, 0.0000000e+00],
       [9.3863750e+04, 1.2732038e+05, 2.4983944e+05, 1.0000000e+00],
       [9.1992390e+04, 1.3549507e+05, 2.5266493e+05, 0.0000000e+00],
       [1.1994324e+05, 1.5654742e+

In [8]:
y=a.iloc[:,4].values
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [9]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression().fit(x,y)
regressor

LinearRegression()

In [10]:
print(regressor.coef_)
print(regressor.intercept_)

[  0.80575968  -0.02682585   0.02722767 -22.32057723]
50142.50644347625


In [11]:
import numpy as np
new_ytopredict=np.array([[72107.6,127864.55,353183.81,2]])
regressor.predict(new_ytopredict)

array([114385.5581763])

In [12]:
import pickle
pickle.dump(regressor,open('multilinear.pkl','wb'))

In [13]:
model=pickle.load(open('multilinear.pkl','rb'))

In [35]:
from tkinter import *
import pickle
model=pickle.load(open('multilinear.pkl','rb'))
root=Tk()
root.title('Profit Prediction')
root.geometry('400x300')
def predictvalue():
    xvalue=[]
    RD=float(v.get())
    xvalue.append(RD)
    Admin=float(a.get())
    xvalue.append(Admin)
    Marketing=float(b.get())
    xvalue.append(Marketing)
    State=(SV.get())
    if State=="New York":
        xvalue.append(2)
    elif State=="California":
        xvalue.append(0)
    else:
        xvalue.append(1)
    ypredict=[np.array(xvalue)]
    o.set(model.predict(ypredict))
Label(root,text="R&D Spend").grid(row=0,column=0)
v=StringVar()
Entry(root,textvariable=v).grid(row=0,column=1)
Label(root,text="Administration").grid(row=1,column=0)
a=StringVar()
Entry(root,textvariable=a).grid(row=1,column=1)
Label(root,text="Marketing Spend").grid(row=2,column=0)
b=StringVar()
Entry(root,textvariable=b).grid(row=2,column=1)
Label(root,text="State").grid(row=3,column=0)
Statevalue=['New York','California','Florida']
SV=StringVar(root)
SV.set('Select State from dropdown')
OptionMenu(root,SV,*Statevalue).grid(row=3,column=1)
Button(root,text='Submit',command=predictvalue).grid(row=5,column=1)
Label(root,text="Profit predicted").grid(row=6,column=0)
o=StringVar()
Entry(root,textvariable=o).grid(row=6,column=1)
root.mainloop()